name: nightly

on:
  schedule:
    - cron: '0 13 * * *'


jobs:
  build:
    if: github.repository == 'OS-Q/T51D'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, ubuntu-16.04]
        ESP8266_RTOS_SDK:
          - "v3.3"
          - "v3.4"
        xtensa-lx106-elf:
          - "1.22.0"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: install xtensa-lx106-elf
        if: matrix.xtensa-lx106-elf == '1.22.0'
        run: |
          sudo apt update
          sudo apt install -y gcc git wget make libncurses-dev flex bison python python-serial ninja-build
          wget https://dl.espressif.com/dl/xtensa-lx106-elf-linux64-1.22.0-100-ge567ec7-5.2.0.tar.gz
          tar -xzf ./xtensa-lx106-elf-linux64-1.22.0-100-ge567ec7-5.2.0.tar.gz

      - name: install ESP8266_RTOS_SDK
        if: matrix.ESP8266_RTOS_SDK == 'v3.3'
        run: |
          wget https://github.com/espressif/ESP8266_RTOS_SDK/releases/download/v3.3-rc1/ESP8266_RTOS_SDK-v3.3-rc1.zip
          unzip ESP8266_RTOS_SDK-v3.3-rc1.zip
          python -m pip install --user -r ./ESP8266_RTOS_SDK/requirements.txt


      - name: install ESP8266_RTOS_SDK
        if: matrix.ESP8266_RTOS_SDK == 'v3.4'
        run: |
          wget https://github.com/espressif/ESP8266_RTOS_SDK/releases/download/v3.3-rc1/ESP8266_RTOS_SDK-v3.4.zip
          unzip ESP8266_RTOS_SDK-v3.4.zip
          python -m pip install --user -r ./ESP8266_RTOS_SDK/requirements.txt

      - name: build
        id: script
        run: |
          export PATH="$PATH:$PWD/xtensa-lx106-elf/bin"
          export IDF_PATH=$PWD/ESP8266_RTOS_SDK
          echo "FIRMWARE=$PWD/DAP/build" >> $GITHUB_ENV
          python DAP/idf.py fullclean
          python DAP/idf.py build
          echo "::set-output name=status::success"
